### ISSUE TITLE
too repetitive

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-inclusion#11]
From Laura Keen: https://lists.w3.org/Archives/Public/wai-eo-editors/2016Nov/0003.html

**Comment by shawna-slh** [comment]
I took a read through with this in mind. I agree there is some repetition, however, I think it's more helpful than annoying. The info that is somewhat repeated is in a difference context and I think it's important to cover it in both places. Also, if someone reads only a specific section and not the whole page, it's good to have the important points included in that section.

Having said that, I certainly would welcome any specific suggestions for edits to address this (and other) issues! :)

**Comment by sharronrush** [comment]
hmmm, so let's think this through...veiwed with Laura's lens, it truly is a quite seriously repetitive series of statements.  I have not paid too much attention to it because frankly I have had my doubts that very many people will ever actually read it.  I am reconsidering its value since the overlaps seem to conflate the "aspects" even further and can end by confusing people more than illuminating much of anything.  Also, I think it is a mistake to write a repetitive document because some people may read only one part.  That is their choice as readers and it may not be fair to  make other readers slog through  repeated reworded statements simply to meet the needs of skimmers. I will make a point to talk to Laura and see what she was getting at. I think we actually could significantly shorten it, perhaps by as much as half.

**Comment by shawna-slh** [comment]
Specific suggestions for edits welcome!

**Comment by lakeen** [comment]
I have re-read this and do have specific edits.  Should I create a separate issue for each as it may be easier to accept/reject my suggestions?

**Comment by shawna-slh** [comment]
Great! If you're doing edits and pull requests, then usually best to have separate ones.

If you're just creating issues, the main consideration is managing comments on them. If there are multiple points in one issue, it's harder to follow if comment thread gets long. However, if there are strongly related edits suggestions, you could batch them into one issue...

**Comment by lakeen** [comment]
I tried to add a new pull request but I'm not able to for some reason. So should I create a new issue for editorial comments?

**Comment by shawna-slh** [comment]
Give me a call and I'll see if I can get pull request to work for you: 617-395-7664

**Comment by shawna-slh** [comment]
Laura put specific edit suggestions in GitHub as pull requests.
