### ISSUE TITLE
Accessibility & Usability Section - sentence accuracy

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-inclusion#22]
In the first bullet "Requirements that are more specific to people with disabilities," The last sentence states:
> Most of these requirements are technical and relate to the underlying code rather than to the visual appearance.

Is this really accurate. Many of the requirements (success criteria) _are_ visual. Is there a different way to say this, or just leave it out?

[strong about accuracy]
[mild about removing it vs. rewording]

**Comment by shawna-slh** [comment]
While it's true that many of the SC are visual, most of those fit in the category of the next bullet "Requirements that are also general usability principles". Of the "Requirements that are more specific to people with disabilities" -- which is the bullet that this sentence is in, I think all but one of those is not visual. Here is a *quick* pass (not necessarily accurate) at figuring that out:

•	[not visual] 1.1 Provide text alternatives for any non-text content so that it can be changed into other forms people need, such as large print, braille, speech, symbols or simpler language.
•	[not visual] 1.2 Provide alternatives for time-based media.
•	[not visual, also general usability principles?] 1.3 Create content that can be presented in different ways (for example simpler layout) without losing information or structure.
•	[also general usability principles] 1.4 Make it easier for users to see and hear content including separating foreground from background.
•	[not visual] 2.1 Make all functionality available from a keyboard.
•	[also general usability principles] 2.2 Provide users enough time to read and use content.
•	[visual] 2.3 Do not design content in a way that is known to cause seizures.
•	[also general usability principles] 2.4 Provide ways to help users navigate, find content, and determine where they are.
•	[also general usability principles] 3.1 Make text content readable and understandable.
•	[also general usability principles] 3.2 Make Web pages appear and operate in predictable ways.
•	[also general usability principles] 3.3 Help users avoid and correct mistakes.
•	[not visual] 4.1 Maximize compatibility with current and future user agents, including assistive technologies.

**Comment by bakkenb** [comment]
Thank you for clearing this up for me Shawn. I was misreading the intention of the contents of the first bullet. Now that I read the bold for each bullet it makes sense, and the sentence is accurate.
